# set(DEVICE_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR})
set(DEVICE_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/3rd/libsophon-0.4.11)
set(DEVICE_HEADERS ${DEVICE_ROOT_DIR}/include)
set(DEVICE_LIB_DIR ${DEVICE_ROOT_DIR}/lib)

set(BMLIB_LIB ${DEVICE_LIB_DIR}/libbmlib.so)
set(BMRT_LIB ${DEVICE_LIB_DIR}/libbmrt.so)
set(BMCV_LIB ${DEVICE_LIB_DIR}/libbmcv.so)
set(BMMODEL_LIB ${DEVICE_LIB_DIR}/libbmmodel.so)
set(BMVD_LIB ${DEVICE_LIB_DIR}/libbmvd.so)
set(BMVENC_LIB ${DEVICE_LIB_DIR}/libbmvenc.so)

add_library(bmlib SHARED IMPORTED)
set_target_properties(bmlib PROPERTIES
    IMPORTED_LOCATION ${BMLIB_LIB}
    INTERFACE_INCLUDE_DIRECTORIES "${DEVICE_HEADERS}"
)

add_library(bmrt SHARED IMPORTED)
set_target_properties(bmrt PROPERTIES
    IMPORTED_LOCATION ${BMRT_LIB}
    INTERFACE_INCLUDE_DIRECTORIES "${DEVICE_HEADERS}"
)

add_library(bmcv SHARED IMPORTED)
set_target_properties(bmcv PROPERTIES
    IMPORTED_LOCATION ${BMCV_LIB}
    INTERFACE_INCLUDE_DIRECTORIES "${DEVICE_HEADERS}"
)

add_library(bmmodel SHARED IMPORTED)
set_target_properties(bmmodel PROPERTIES
    IMPORTED_LOCATION ${BMMODEL_LIB}
    INTERFACE_INCLUDE_DIRECTORIES "${DEVICE_HEADERS}"
)

add_library(bmvd SHARED IMPORTED)
set_target_properties(bmvd PROPERTIES
    IMPORTED_LOCATION ${BMVD_LIB}
    INTERFACE_INCLUDE_DIRECTORIES "${DEVICE_HEADERS}"
)

add_library(bmvenc SHARED IMPORTED)
set_target_properties(bmvenc PROPERTIES
    IMPORTED_LOCATION ${BMVENC_LIB}
    INTERFACE_INCLUDE_DIRECTORIES "${DEVICE_HEADERS}"
)

install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/3rd/libsophon-0.4.11/lib/
    DESTINATION lib
    FILES_MATCHING
        PATTERN "*so*"
)
